// <auto-generated />
using System;
using FridayExam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FridayExam.Migrations
{
    [DbContext(typeof(HomeContext))]
    [Migration("20200124205616_fiveMigration")]
    partial class fiveMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FridayExam.Models.Club", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CoordinatorID");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DateOfClub")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Duration")
                        .IsRequired();

                    b.Property<string>("DurationUnit")
                        .IsRequired();

                    b.Property<DateTime?>("Time")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("ID");

                    b.HasIndex("CoordinatorID");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FridayExam.Models.Participent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClubID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("ClubID");

                    b.HasIndex("UserID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("FridayExam.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FridayExam.Models.Club", b =>
                {
                    b.HasOne("FridayExam.Models.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FridayExam.Models.Participent", b =>
                {
                    b.HasOne("FridayExam.Models.Club", "Club")
                        .WithMany("Participents")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FridayExam.Models.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
